--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/PureChat
build-by-default: true
branches:
- PM5
- PM4
projects:
  PureChat:
    path: ""
    lint:
      phpstan: false
...
